version: '3'
services:
  node1:
    image: agent
    container_name: node-1
    volumes:
      - ./shared:/shared
    ports:
      - 8888:8888
      - 80:5000
      - 15000:15000
    networks:
      my_network:
        aliases:
          - node1
        ipv4_address: 192.168.1.1
  node2:
    image: agent
    container_name: node-2
    volumes:
      - ./shared:/shared
    ports:
      - 8889:8888
      - 81:5000
      - 15001:15000
    networks:
      my_network:
        aliases:
          - node2
        ipv4_address: 192.168.1.2
  node3:
    image: agent
    container_name: node-3
    volumes:
      - ./shared:/shared
    ports:
      - 8890:8888
      - 82:5000
      - 15002:15000
    networks:
      my_network:
        aliases:
          - node3
        ipv4_address: 192.168.1.3
  node4:
    image: agent
    container_name: node-4
    volumes:
      - ./shared:/shared
    ports:
      - 8891:8888
      - 83:5000
      - 15003:15000
    networks:
      my_network:
        aliases:
          - node4
        ipv4_address: 192.168.1.4
  node5:
    image: agent
    container_name: node-5
    volumes:
      - ./shared:/shared
    ports:
      - 8892:8888
      - 84:5000
      - 15004:15000
    networks:
      my_network:
        aliases:
          - node5
        ipv4_address: 192.168.1.5
  aggregation_server:
    image: server
    container_name: aggregation_server
    volumes:
      - ./shared:/shared
    ports:
      - 8893:8888
      - 85:5000
      - 15005:15000
    networks:
      my_network:
        aliases:
          - aggregation_server
        ipv4_address: 192.168.1.6
networks:
  my_network:
    ipam:
      config:
        - subnet: 192.168.0.0/16