version: '3'
services:
  node1:
    image: agent
    container_name: node-1
    volumes:
      - ./ssl/client1_cert.pem:/clientkey/client_cert.pem  # Mount specific client certificate and key
      - ./ssl/client1_key.pem:/clientkey/client_key.pem
      - ./ssl/root_cert.pem:/clientkey/root_cert.pem
    ports:
      - 8888:8888
      - 80:5000
      - 15000:15000
      - 12345:12345
    networks:
      my_network:
        aliases:
          - node1
        ipv4_address: 192.168.1.1
  node2:
    image: agent
    container_name: node-2
    volumes:
      - ./ssl/client2_cert.pem:/clientkey/client_cert.pem  # Mount specific client certificate and key
      - ./ssl/client2_key.pem:/clientkey/client_key.pem
      - ./ssl/root_cert.pem:/clientkey/root_cert.pem
    ports:
      - 8889:8888
      - 81:5000
      - 15001:15000
      - 12346:12345
    networks:
      my_network:
        aliases:
          - node2
        ipv4_address: 192.168.1.2
  node3:
    image: agent
    container_name: node-3
    volumes:
      - ./ssl/client3_cert.pem:/clientkey/client_cert.pem  # Mount specific client certificate and key
      - ./ssl/client3_key.pem:/clientkey/client_key.pem
      - ./ssl/root_cert.pem:/clientkey/root_cert.pem
    ports:
      - 8890:8888
      - 82:5000
      - 15002:15000
      - 12347:12345
    networks:
      my_network:
        aliases:
          - node3
        ipv4_address: 192.168.1.3
  node4:
    image: agent
    container_name: node-4
    volumes:
      - ./ssl/client4_cert.pem:/clientkey/client_cert.pem  # Mount specific client certificate and key
      - ./ssl/client4_key.pem:/clientkey/client_key.pem
      - ./ssl/root_cert.pem:/clientkey/root_cert.pem
    ports:
      - 8891:8888
      - 83:5000
      - 15003:15000
      - 12348:12345
    networks:
      my_network:
        aliases:
          - node4
        ipv4_address: 192.168.1.4
  node5:
    image: agent
    container_name: node-5
    volumes:
      - ./ssl/client5_cert.pem:/clientkey/client_cert.pem  # Mount specific client certificate and key
      - ./ssl/client5_key.pem:/clientkey/client_key.pem
      - ./ssl/root_cert.pem:/clientkey/root_cert.pem
    ports:
      - 8892:8888
      - 84:5000
      - 15004:15000
      - 12349:12345
    networks:
      my_network:
        aliases:
          - node5
        ipv4_address: 192.168.1.5
  aggregation_server:
    image: server
    container_name: aggregation_server
    volumes:
      - ./ssl/server_cert.pem:/servercert/server_cert.pem  # Mount specific client certificate and key
      - ./ssl/server_key.pem:/servercert/server_key.pem
      - ./ssl/root_cert.pem:/servercert/root_cert.pem
    ports:
      - 8893:8888
      - 85:5000
      - 15005:15000
      - 12350:12345
    networks:
      my_network:
        aliases:
          - aggregation_server
        ipv4_address: 192.168.1.6
  key_generation_center:
    image: agent
    container_name: key_generation_center
    volumes:
      - ./shared:/shared
      - ./ssl:/keys
    ports:
      - 8894:8888
      - 86:5000
      - 15006:15000
      - 12351:12345
    networks:
      my_network:
        aliases:
          - aggregation_server
        ipv4_address: 192.168.1.7
networks:
  my_network:
    ipam:
      config:
        - subnet: 192.168.0.0/16